### ISSUE TITLE
user-supplied class_data is being ignored during training

### ISSUE THREAD

**Issue by zeke** [replicate/dreambooth#19]
From user `rok` in Discord:

> I put my class photos into a "data" directory, zipped it up, uploaded it via Replicate --- same as for the instance_data. I then used the URL of the class data for the class_data parameter to the DreamBooth API. However, when looking at the training logs , I can see that the training includes "Generating class images", which should not be the case. Please advise. 

Discord thread: https://discord.com/channels/775512803439280149/1049086988566929468/1049086988566929468

**Comment by evilstreak** [comment]
This was down to the version of Dreambooth we were using via the experimental API. I've updated that to the latest version, and this should now be resolved.
