### ISSUE TITLE
Piping this model into inpainting?

### ISSUE THREAD

**Issue by cinjon** [replicate/dreambooth#24]
I would like to train a dreambooth model and then pipe it into an inpainting setup. The ideal is that I just use the API to do it, then pipe from the published model to inpainting. Is that possible? I can't tell. I understand that I could do this, then get the weights myself and take that elsewhere, but it would be fantastic if I could pipe it through your service to the end.

**Comment by anotherjesse** [comment]
Good idea - we have a bug in the inference template for this here: https://github.com/replicate/dreambooth-template/issues/25

**Comment by usama-gh** [comment]
is it resolved?
