### ISSUE TITLE
Error with ckpt file

### ISSUE THREAD

**Issue by zweedao** [replicate/dreambooth#35]
Hi, 

I'm using the Demo tool here: https://replicate.com/replicate/dreambooth/run

I tried to use this ckpt file: https://huggingface.co/timbrooks/instruct-pix2pix/blob/main/instruct-pix2pix-00-22000.ckpt

But it throws this error: "This file type is not supported. Try another that is plain text, audio, image, or video."
When I remove the ckpt file, the error goes away.

Could you please advise? Thanks!

**Comment by Rashxz** [comment]
Im facing this too, any help?

**Comment by zweedao** [comment]
I figured out Dreambooth doesn't really work with instruct-pix2pix for now, because of how the models are implemented. This is not a bug. Closing this for now.

**Comment by thesrs02** [comment]
Doesn't seem to work with any custom CKPT

**Comment by Rashxz** [comment]
I had to use the API to get it to work.
