### ISSUE TITLE
make it obvious how to name the custom concept keyword

### ISSUE THREAD

**Issue by zeke** [replicate/dreambooth#6]
`sks` is the default string (keyword?) that represents the trained concept. Is there an input parameter to the model that can be set to customize this keyword?

cc @chenxwh

**Comment by chenxwh** [comment]
refer to the README on https://replicate.com/replicate/dreambooth maybe?

**Comment by zeke** [comment]
https://replicate.com/blog/dreambooth-api covers it pretty well.

> `a [identifier] [class noun]`, where identifier is some rare token. In the example above we're using cjw, but you can use any string you like. For best results, use an identifier containing 3 Unicode characters, without spaces.

**Comment by zeke** [comment]
Resolved by https://github.com/replicate/dreambooth/blob/88ef90b6bcda8e2a501b365f49fc04c3e7263695/predictor.py#L63
